"""Auto-detected migration

Revision ID: 7b86b5f09eb9
Revises: 
Create Date: 2024-10-02 20:29:54.742039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b86b5f09eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abouut')
    op.drop_table('contact')
    with op.batch_alter_table('about_me', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_me', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('designation')

    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('button_text', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contact_link', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abouut',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
