"""Auto-detected migration

Revision ID: 98580f3fc191
Revises: ebcf218be7bd
Create Date: 2024-10-03 13:39:25.410663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98580f3fc191'
down_revision = 'ebcf218be7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    with op.batch_alter_table('counter_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter_fact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('title')

    op.create_table('counter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('happy_clients', sa.INTEGER(), nullable=True),
    sa.Column('support_team', sa.INTEGER(), nullable=True),
    sa.Column('sales_count', sa.INTEGER(), nullable=True),
    sa.Column('awards', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
